spring:
  datasource:                                             ## 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource              # 数据源 HikariCP
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动
    url: jdbc:mysql://101.42.168.101:3306/itzixi-pay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: liuhao123@
  redis:
    database: 0
    host: 101.42.168.101
    port: 6379
    password: liuhao123@
